services:
  server:
    image: node:alpine
    volumes:
      - ./server:/server
    working_dir: /server
    command: sh -c "npm i && npm run dev"
    ports:
      - 3001:3001
  client:
    image: node:alpine
    volumes:
      - ./client:/client
    working_dir: /client
    command: sh -c "npm i && npm run dev"
    ports:
      - 3000:3000
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db_scripts:/docker-entrypoint-initdb.d  #database setup scripts
      - persistentDatabase:/var/lib/mysql
volumes:
  persistentDatabase: