services:
  server:
    image: node:alpine
    volumes:
      - ./server:/server
    working_dir: /server
    command: sh -c "npm i && npm run nodemon"
    ports:
      - 3001:3001
  client:
    image: node:alpine
    volumes:
      - ./client:/client
    working_dir: /client
    command: sh -c "npm i && npm start"
    ports:
      - 0.0.0.0:3000:3000
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db_scripts:/docker-entrypoint-initdb.d