services:
  # nginx:
  #   image: nginx:alpine
  #   depends_on:
  #     - server
  #     - client
  #   ports:
  #     - 80:80
  #   volumes:
  #     - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  server:
    image: node:alpine
    depends_on:
      - db
    volumes:
      - ./server:/server
    working_dir: /server
    command: sh -c "npm i && npm run dev"
    environment:
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: finance
    ports:
      - 3001:3001
  client:
    image: node:alpine
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./client:/client
    working_dir: /client
    command: sh -c "npm i && npm run dev"
    ports:
      - 3000:3000
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: finance
    volumes:
      - ./db_scripts:/docker-entrypoint-initdb.d  #database setup scripts
      # - persistentDatabase:/var/lib/mysql

#Commented out for experimentation reasons
# volumes:
#   persistentDatabase: